services:
  - type: web
    name: ab-management-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AB_WEB_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
